name: Release
run-name: ${{ github.actor }} building a new release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build-prod --if-present
      - name: "Get version"
        run: |
          sed -n 's/.*"version": "\([^"]\+\).*/\1/p' ./dist/system.json
      - name: Zip files
        working-directory: ./dist
        run: zip -r ./heart.zip ./*
      - uses: ncipollo/release-action@v1
          with: 
            artifacts: "./dist/system.json,./dist/heart.zip"
            tag: ${{ env.systemVersion }}-test
  release:
    runs-on: ubuntu-latest